// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Courses documents
 */
interface CoursesDocumentData {
  /**
   * Imagem do Curso field in *Courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.course_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  course_image: prismic.ImageField<never>;

  /**
   * Nome do Curso field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do Curso
   * - **API ID Path**: courses.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Modalidade field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Modalidade
   * - **API ID Path**: courses.modality
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  modality: prismic.KeyTextField;

  /**
   * Valor Total field in *Courses*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Valor Total
   * - **API ID Path**: courses.total_value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  total_value: prismic.NumberField;

  /**
   * Desconto field in *Courses*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Desconto
   * - **API ID Path**: courses.discount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  discount: prismic.NumberField;

  /**
   * Informação do Curso field in *Courses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Informação do Curso
   * - **API ID Path**: courses.course_information
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  course_information: prismic.RichTextField;
}

/**
 * Courses document from Prismic
 *
 * - **API ID**: `courses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoursesDocumentData>,
    "courses",
    Lang
  >;

/**
 * Content for FARVALLE documents
 */
interface FarvalleDocumentData {
  /**
   * Imagem do Curso field in *FARVALLE*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.course_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  course_image: prismic.ImageField<never>;

  /**
   * Nome do Curso field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Modalidade field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.modality
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  modality: prismic.KeyTextField;

  /**
   * Valor Total field in *FARVALLE*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.total_value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  total_value: prismic.NumberField;

  /**
   * Desconto field in *FARVALLE*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  discount: prismic.NumberField;

  /**
   * Informação do Curso field in *FARVALLE*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.course_information
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  course_information: prismic.RichTextField;

  /**
   * Disciplina 1 field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discipline_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_1: prismic.KeyTextField;

  /**
   * Disciplina 2 field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discipline_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_2: prismic.KeyTextField;

  /**
   * Disciplina 3 field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discipline_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_3: prismic.KeyTextField;

  /**
   * Disciplina 4 field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discipline_4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_4: prismic.KeyTextField;

  /**
   * Disciplina 5 field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discipline_5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_5: prismic.KeyTextField;

  /**
   * Disciplina 6 field in *FARVALLE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle.discipline_6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_6: prismic.KeyTextField;
}

/**
 * FARVALLE document from Prismic
 *
 * - **API ID**: `farvalle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FarvalleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FarvalleDocumentData>,
    "farvalle",
    Lang
  >;

/**
 * Content for FARVALLE Fotos documents
 */
interface FarvallePhotosDocumentData {
  /**
   * Imagem 01 field in *FARVALLE Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle_photos.image_01
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_01: prismic.ImageField<never>;

  /**
   * Imagem 02 field in *FARVALLE Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle_photos.image_02
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_02: prismic.ImageField<never>;

  /**
   * Imagem 03 field in *FARVALLE Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle_photos.image_03
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_03: prismic.ImageField<never>;

  /**
   * Imagem 04 field in *FARVALLE Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: farvalle_photos.image_04
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_04: prismic.ImageField<never>;
}

/**
 * FARVALLE Fotos document from Prismic
 *
 * - **API ID**: `farvalle_photos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FarvallePhotosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FarvallePhotosDocumentData>,
    "farvalle_photos",
    Lang
  >;

/**
 * Content for FAZAG documents
 */
interface FazagDocumentData {
  /**
   * Imagem do Curso field in *FAZAG*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.course_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  course_image: prismic.ImageField<never>;

  /**
   * Nome do Curso field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Modalidade field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.modality
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  modality: prismic.KeyTextField;

  /**
   * Valor Total field in *FAZAG*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.total_value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  total_value: prismic.NumberField;

  /**
   * Desconto field in *FAZAG*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  discount: prismic.NumberField;

  /**
   * Informação do Curso field in *FAZAG*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.course_information
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  course_information: prismic.RichTextField;

  /**
   * Disciplina 1 field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discipline_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_1: prismic.KeyTextField;

  /**
   * Disciplina 2 field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discipline_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_2: prismic.KeyTextField;

  /**
   * Disciplina 3 field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discipline_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_3: prismic.KeyTextField;

  /**
   * Disciplina 4 field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discipline_4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_4: prismic.KeyTextField;

  /**
   * Disciplina 5 field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discipline_5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_5: prismic.KeyTextField;

  /**
   * Disciplina 6 field in *FAZAG*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag.discipline_6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discipline_6: prismic.KeyTextField;
}

/**
 * FAZAG document from Prismic
 *
 * - **API ID**: `fazag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FazagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FazagDocumentData>, "fazag", Lang>;

/**
 * Content for FAZAG Fotos documents
 */
interface FazagPhotosDocumentData {
  /**
   * Imagem 01 field in *FAZAG Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag_photos.image_01
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_01: prismic.ImageField<never>;

  /**
   * Imagem 02 field in *FAZAG Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag_photos.image_02
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_02: prismic.ImageField<never>;

  /**
   * Imagem 03 field in *FAZAG Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag_photos.image_03
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_03: prismic.ImageField<never>;

  /**
   * Imagem 04 field in *FAZAG Fotos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fazag_photos.image_04
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_04: prismic.ImageField<never>;
}

/**
 * FAZAG Fotos document from Prismic
 *
 * - **API ID**: `fazag_photos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FazagPhotosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FazagPhotosDocumentData>,
    "fazag_photos",
    Lang
  >;

/**
 * Content for Faculdades documents
 */
interface UniversityDocumentData {
  /**
   * Nome da Faculdade field in *Faculdades*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome da Faculdade
   * - **API ID Path**: university.university
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  university: prismic.KeyTextField;

  /**
   * Imagens da Faculdade field in *Faculdades*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: university.university_images
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  university_images: prismic.ImageField<
    "image_01" | "image_02" | "image_03" | "image_04"
  >;

  /**
   * embed_maps field in *Faculdades*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link do Google Maps (Embed)
   * - **API ID Path**: university.embed_maps
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  embed_maps: prismic.LinkField;
}

/**
 * Faculdades document from Prismic
 *
 * - **API ID**: `university`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UniversityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UniversityDocumentData>,
    "university",
    Lang
  >;

export type AllDocumentTypes =
  | CoursesDocument
  | FarvalleDocument
  | FarvallePhotosDocument
  | FazagDocument
  | FazagPhotosDocument
  | UniversityDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CoursesDocument,
      CoursesDocumentData,
      FarvalleDocument,
      FarvalleDocumentData,
      FarvallePhotosDocument,
      FarvallePhotosDocumentData,
      FazagDocument,
      FazagDocumentData,
      FazagPhotosDocument,
      FazagPhotosDocumentData,
      UniversityDocument,
      UniversityDocumentData,
      AllDocumentTypes,
    };
  }
}
