
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { Header } from "./components/Header";
import { createContext } from "react";
import { UserProvider } from "./components/contexts/user-provider";
import { Inter } from 'next/font/google'
import { inter, oswald, poppins } from "./fonts";
import { MetaPixel } from "./components/MetaPixel";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Motiva Bolsas",
  description: "Generated by create next app",

};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-BR"> 
    <head>
    <MetaPixel/>
    </head>
    <UserProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className}`}>
      <header>
        <Header/>
      </header>
      <main>
      {children}    
      </main> 
      </body>
    </UserProvider>
    </html>
  );
}
